version: '3'

services:

    mysql-server:
        image:                   mysql:5.7
        hostname:                mysql-server
        environment:
            MYSQL_ROOT_PASSWORD: userpass
        command:                 ['mysqld','--max_allowed_packet=1000M -u root -p roe_iot < roe_iot.sql','--default-time-zone=-03:00']
        volumes:
            -                    ./db/dumps:/docker-entrypoint-initdb.d
            -                    ./db/data:/var/lib/mysql
        networks:
            -                    ROE-IOT

    mysql-admin:
        image:                   phpmyadmin/phpmyadmin
        environment:
            PMA_HOST:            mysql-server
            PMA_PORT:            3306
            MYSQL_ROOT_PASSWORD: userpass

        networks:
            -                    ROE-IOT
        depends_on:
            -                    mysql-server
        ports:
            -                    "8001:80"
    node-backend:
        image:                   abassi/nodejs-server:10.0-dev
        volumes:
            -                    ./api:/home/node/app/src
        networks:
            -                    ROE-IOT
        depends_on:
            -                    mysql-server
        ports:
            -                    "8000:3000"
        command:                 nodemon /home/node/app/src/index.js

networks:
       ROE-IOT:
        driver:                  bridge
